config/routes.rb
Apparent::Application.routes.draw do
  
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
    
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    
    if @category.update_attributes(params[:category])
      redirect_to categories_path
    else
      render :edit
    end
  end
  
  def destroy
    Category.destroy(params[:id])
    
    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>
	
	<%= f.submit submit_text %>
  
<% end %>

app/views/categories/edit.html.erb
<%= render :partial => 'form', :locals => { :submit_text => 'Update' }%>

app/views/categories/index.html.erb
<h2>Categories</h2>

<%= link_to 'Create a new category', new_category_path %>

<ol>
<% @categories.each do |category| %>
	<li><%= link_to category.name, edit_category_path(category) %> (<%= link_to 'delete', category_path(category), :method => :delete %>)</li>
<% end %>
<ol>

app/views/categories/new.html.erb
<%= render :partial => 'form', :locals => { :submit_text => 'Create' }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apparent</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	
	<h1>Apparent</h1>
	
<%= yield %>

</body>
</html>